apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAYYiKTAeBbbxQ1mdB4BMHnzAtibQWZTzNKUgRNcmmT48zfDr9x8qIh7I4a7H08ojAwejZcbceTKK81Tii9sUEl4ZmrEmnCZLDlKW2z5BcAoWoqsOLfjJ8V9ZG3kS1H6Mnwfeg9nDHAoyWyvybzJllBlIE39lfvn4LfTayDe+ENm6p4wdExO7j0k0WDg0r9flRrU1GEC8ltasIdQNYM+sW8PzzlD2AUEWOOcvoTiNq6Z0DgtlzII+fzB1gv+U74y25TWL53SSGzS6Eo1b8GdxdmCAcyZDBmO5l14f2imTyG3fZ//c4TlPEFBtG4hWfXKg0QPTnRW11qc0r7zuARUvoIu8AwJz+I3Bd5yg5Jg8kLhEa1yLOag9WJAkbUQl4MG0pRhChVIuDkyMxjl4Ygug57nisf/Cdtab7819NRCFr8gVOOcF9lasWgfJD57xU/+Op/irBkkMSC6nkw72+jqaqPqlKBdlva8U4+jqBzE1OM6Tblkvkbw0pB/Ty2q3ZLELBsZDSXtgFtjrm9QtKusPwVZ2eTTs0Xr60CRUGO2SIYtozbZJJGzoHEBfMNJbTsdz3U8atlP47s8wXfSqsPITjTxbYCQ+xIyLFKt9W88BnPy7yJGKYCqEczqyOzYssMm2C3Ub4xP/0wELPge8+uLECe2ZLKcTOP/4fpKeqw8rlHigWTbBu1sb/0KZUiCGsnQegOvKObkLiJhNrqMKutP2xOaxyRxnlnA8CKM5pp818xbe0vRrOB2cSHD00CC2ek1dzRtf/8UUnwT8pDgr+m8KNjsGMcRgnTUpbM5BD1cTsdOJS3nCoIgbGtTKiel+RkkxirAvpK1euyrJ57hj1JgNLjJijKA0Sd0DpqigQ3zV1RnkPZQKdEzoLldoBij6XgomzPP0eqxTF+HWXl/Pb/rQMh5E5dyg4Bgb5P48jmP1CNRDfKYcUYVzDXVegBlH5A949eg+qGI1FBm/1+jE9pPw3eOIlefzFefktR51zWck1/sN1qX7IiMaRv4VtsTVzwxJL9UEF6dVdJYS1MM5nvJf7qEVVjUvqpc3zLeliqYOKv+lw5BLDL3fqAY+8bUFicTGeHYXy/IbKK5w13g90Y0nVXCpDo8a8Xi25vlH/i2aCDwOfntt87+8gUiouO3LdKoZJT4JkyrOQn1NaIkmJx2FXsR0AdmuDd9ybB6Ymg2M6dMZSuy5KDSo5RO/uhd1uPUaPFX5ES4sD+iq9nuszivJF5RQ3hb7UQ/3CcIBOlRKGrgogNfdqNQPl/+gtU9IZ4Y3bBwfVXg7L816fA75MubPIJkoNf+YteJmOjYMuMa7fJ8YmnTwb+QoEvvGfhov9Aubcj5dphESCNx4q3VZdseY5jMNkOsM086WgHmCT4DyilS+IpVzeKMT7Zc779Xv3GTZQHmlTiPHIuWYcN7mljMYEO2mtq0p4MbCPqKTCJ6zZLvTVuHMGaFR+ob8VoErsTvGbqcQ+MZdxRDoL4YMo+t2+OTpE5BhQG0ywROoqB8DJBpi4OOVWBIu3k9PA=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
