apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC2OKojpE+R9ST+fx0moxVGF4+qu1B9YUDLG3NOLnle7hmzROAh0G2GGw/vHBWbycvmHVg/AlUTscPK8ki7kcb4UHBIkvHhYMr1k9I7RBguowl9+gYvm/8D0ppvEz71z5paQgG7rzn0EsIrhtXmMn7gD1XjEWSpxmzE0c5X6Ow3MI+25hjk2f8lWfU0ns7ZAjNg2psEvK8W9IGBDgj03aROzUuBmUI0uR94rO1ezaSiqaLyQJNZBoUtHa4EeOKHdZBgcGy+dR0ln89EFLVfY8QKZxo5vLCxuFLBKs92B/WZM0+1VBqqzdxn387v66tiVrmwRBs3kxuU5U501GyBPFkzgHTM8lkGiT+drduGnCwTpOZUYj4sZPNPbew7knHrX5jDh5hwkcFmYIbhjKV9N+EZeT+ZSLcVSZ8oQ4rC2QYgYXQtXqjwyoDnNSEfEnjkXZnr5Qa/zcsQFIYSDtrX1p6Fp5QnhUPFFHe9vZx5LWrjJ57TYohfnK9dW4nGnH9V8ya7oTbI8+f13A++rcC4/v6V2SV1SW+swb1ANE7ebgBfMFo+dO8fPaXgB6mBvg4fSLEaSuOc2rWc9qE5G+hOT4me5F/tQMIInGRyfb8DJkP8arVA2bTEu6gOC0EthTsmdhadk2dE4/yvQin6l3cOtFZpcuw4dirYRqHRfiZwGwoW6PcLxgpuWak0E1R4wiXa4goJgPpTuhhm8pZchl9KKmFI9zjoJA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
