apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: taxi2
  namespace: dev
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: taxi2
    weight: 100
  wildcardPolicy: None
